// <auto-generated />
using System;
using InvestAI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InvestAI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260511173639_AddRailwayData")]
    partial class AddRailwayData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InvestAI.Models.AirportData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AirportDatas");
                });

            modelBuilder.Entity("InvestAI.Models.DistrictAirportDistance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AirportName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("DistanceKm")
                        .HasColumnType("double precision");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DistrictAirportDistances");
                });

            modelBuilder.Entity("InvestAI.Models.DistrictEducation", b =>
                {
                    b.Property<decimal>("EgitimPuani")
                        .HasColumnType("numeric")
                        .HasColumnName("egitim_puani");

                    b.Property<string>("Il")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("il");

                    b.Property<string>("Ilce")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ilce");

                    b.Property<decimal>("IlkogretimOrani")
                        .HasColumnType("numeric")
                        .HasColumnName("ilkogretim_orani");

                    b.Property<decimal>("LiseOrani")
                        .HasColumnType("numeric")
                        .HasColumnName("lise_orani");

                    b.Property<decimal>("UniversiteOrani")
                        .HasColumnType("numeric")
                        .HasColumnName("universite_orani");

                    b.ToTable("district_education", (string)null);
                });

            modelBuilder.Entity("InvestAI.Models.DistrictLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DistrictLocations");
                });

            modelBuilder.Entity("InvestAI.Models.DistrictPopulation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Population")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("DistrictPopulations");
                });

            modelBuilder.Entity("InvestAI.Models.DistrictPortDistance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("DistanceKm")
                        .HasColumnType("double precision");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DistrictPortDistances");
                });

            modelBuilder.Entity("InvestAI.Models.DistrictSectorDistribution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeCount")
                        .HasColumnType("integer")
                        .HasColumnName("employee_count");

                    b.Property<string>("Il")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("il");

                    b.Property<string>("Ilce")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ilce");

                    b.Property<decimal>("Percentage")
                        .HasColumnType("numeric")
                        .HasColumnName("percentage");

                    b.Property<string>("SectorCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sector_code");

                    b.Property<string>("SectorName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sector_name");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.ToTable("district_sector_distribution", (string)null);
                });

            modelBuilder.Entity("InvestAI.Models.DistrictSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DominantSectorCode")
                        .HasColumnType("text")
                        .HasColumnName("dominant_sector_code");

                    b.Property<string>("DominantSectorName")
                        .HasColumnType("text")
                        .HasColumnName("dominant_sector_name");

                    b.Property<string>("Il")
                        .HasColumnType("text")
                        .HasColumnName("il");

                    b.Property<string>("Ilce")
                        .HasColumnType("text")
                        .HasColumnName("ilce");

                    b.Property<int>("TotalEstimatedEmployment")
                        .HasColumnType("integer")
                        .HasColumnName("total_estimated_employment");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.ToTable("district_summary", (string)null);
                });

            modelBuilder.Entity("InvestAI.Models.DogalgazAnaHat", b =>
                {
                    b.Property<bool>("AnaIletimHattiVarMi")
                        .HasColumnType("boolean")
                        .HasColumnName("ana_iletim_hatti_var_mi");

                    b.Property<string>("Il")
                        .HasColumnType("text")
                        .HasColumnName("il");

                    b.Property<string>("Kaynak")
                        .HasColumnType("text")
                        .HasColumnName("kaynak");

                    b.Property<int>("Yil")
                        .HasColumnType("integer")
                        .HasColumnName("yil");

                    b.ToTable("dogalgaz_ana_hat", (string)null);
                });

            modelBuilder.Entity("InvestAI.Models.EnergyData", b =>
                {
                    b.Property<double>("ElektrikErisimOrani")
                        .HasColumnType("double precision")
                        .HasColumnName("elektrik_erisim_orani");

                    b.Property<double>("GesMw")
                        .HasColumnType("double precision")
                        .HasColumnName("ges_mw");

                    b.Property<string>("Il")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("il");

                    b.Property<double>("ResMw")
                        .HasColumnType("double precision")
                        .HasColumnName("res_mw");

                    b.Property<double>("ToplamMw")
                        .HasColumnType("double precision")
                        .HasColumnName("toplam_mw");

                    b.Property<int>("Yil")
                        .HasColumnType("integer")
                        .HasColumnName("yil");

                    b.ToTable("energy_data", (string)null);
                });

            modelBuilder.Entity("InvestAI.Models.GunesSantrali", b =>
                {
                    b.Property<string>("Firma")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("firma");

                    b.Property<string>("Il")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("il");

                    b.Property<double>("KuruluGucMw")
                        .HasColumnType("double precision")
                        .HasColumnName("kurulu_guc_mw");

                    b.Property<string>("SantralAdi")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("santral_adi");

                    b.ToTable("gunes_santralleri", (string)null);
                });

            modelBuilder.Entity("InvestAI.Models.HidroelektrikData", b =>
                {
                    b.Property<string>("Firma")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("firma");

                    b.Property<string>("Il")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("il");

                    b.Property<decimal>("KuruluGucMw")
                        .HasColumnType("numeric")
                        .HasColumnName("kurulu_guc_mw");

                    b.Property<string>("SantralAdi")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("santral_adi");

                    b.ToTable("hidroelektrik_data", (string)null);
                });

            modelBuilder.Entity("InvestAI.Models.IhracatVerisi", b =>
                {
                    b.Property<long>("IhracatUsd")
                        .HasColumnType("bigint")
                        .HasColumnName("ihracat_usd");

                    b.Property<string>("Il")
                        .HasColumnType("text")
                        .HasColumnName("il");

                    b.Property<int>("Yil")
                        .HasColumnType("integer")
                        .HasColumnName("yil");

                    b.ToTable("ihracat_verileri", (string)null);
                });

            modelBuilder.Entity("InvestAI.Models.IlIlceGoc", b =>
                {
                    b.Property<string>("GocDurumu")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("goc_durumu");

                    b.Property<string>("Il")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("il");

                    b.Property<string>("Ilce")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ilce");

                    b.Property<int>("NetGoc")
                        .HasColumnType("integer")
                        .HasColumnName("net_goc");

                    b.Property<int>("Yil")
                        .HasColumnType("integer")
                        .HasColumnName("yil");

                    b.ToTable("il_ilce_goc", (string)null);
                });

            modelBuilder.Entity("InvestAI.Models.IlTarim", b =>
                {
                    b.Property<string>("BasliUrunler")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("basli_urunler");

                    b.Property<decimal>("EkilebilirAlanHa")
                        .HasColumnType("numeric")
                        .HasColumnName("ekilebilir_alan_ha");

                    b.Property<decimal>("EkilebilirAlanOraniPct")
                        .HasColumnType("numeric")
                        .HasColumnName("ekilebilir_alan_orani_pct");

                    b.Property<string>("Il")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("il");

                    b.Property<int>("IlKodu")
                        .HasColumnType("integer")
                        .HasColumnName("il_kodu");

                    b.Property<string>("Kaynak")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kaynak");

                    b.Property<string>("OnerilenYatirimAlani")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("onerilen_yatirim_alani");

                    b.Property<decimal>("SulamaOraniPct")
                        .HasColumnType("numeric")
                        .HasColumnName("sulama_orani_pct");

                    b.Property<decimal>("TarimAlaniHa")
                        .HasColumnType("numeric")
                        .HasColumnName("tarim_alani_ha");

                    b.Property<decimal>("TarimIstihdamiPct")
                        .HasColumnType("numeric")
                        .HasColumnName("tarim_istihdami_pct");

                    b.Property<int>("UrunSayisi")
                        .HasColumnType("integer")
                        .HasColumnName("urun_sayisi");

                    b.Property<decimal>("YatirimPotansiyelSkoru")
                        .HasColumnType("numeric")
                        .HasColumnName("yatirim_potansiyel_skoru");

                    b.Property<string>("YatirimSeviyesi")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("yatirim_seviyesi");

                    b.Property<string>("Yil")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("yil");

                    b.ToTable("il_tarim", (string)null);
                });

            modelBuilder.Entity("InvestAI.Models.InvestAI.Models.IlIlceIssizlik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Il")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("il");

                    b.Property<string>("Ilce")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ilce");

                    b.Property<decimal>("IssizlikOrani")
                        .HasColumnType("numeric")
                        .HasColumnName("issizlik_orani");

                    b.Property<int>("Yil")
                        .HasColumnType("integer")
                        .HasColumnName("yil");

                    b.HasKey("Id");

                    b.ToTable("il_ilce_issizlik", (string)null);
                });

            modelBuilder.Entity("InvestAI.Models.InvestmentSuggestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RegionId")
                        .HasColumnType("integer");

                    b.Property<float>("Score")
                        .HasColumnType("real");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("InvestmentSuggestions");
                });

            modelBuilder.Entity("InvestAI.Models.JeotermalData", b =>
                {
                    b.Property<string>("Firma")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("firma");

                    b.Property<string>("Il")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("il");

                    b.Property<double>("KuruluGucMw")
                        .HasColumnType("double precision")
                        .HasColumnName("kurulu_guc_mw");

                    b.Property<string>("SantralAdi")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("santral_adi");

                    b.ToTable("jeotermal_data", (string)null);
                });

            modelBuilder.Entity("InvestAI.Models.MadenData", b =>
                {
                    b.Property<string>("Il")
                        .HasColumnType("text")
                        .HasColumnName("il");

                    b.Property<int?>("IlKodu")
                        .HasColumnType("integer")
                        .HasColumnName("il_kodu");

                    b.Property<string>("Ilce")
                        .HasColumnType("text")
                        .HasColumnName("ilce");

                    b.Property<string>("Kaynak")
                        .HasColumnType("text")
                        .HasColumnName("kaynak");

                    b.Property<string>("MadenTuru")
                        .HasColumnType("text")
                        .HasColumnName("maden_turu");

                    b.Property<string>("Notlar")
                        .HasColumnType("text")
                        .HasColumnName("notlar");

                    b.Property<string>("RezervDurumu")
                        .HasColumnType("text")
                        .HasColumnName("rezerv_durumu");

                    b.Property<int>("Yil")
                        .HasColumnType("integer")
                        .HasColumnName("yil");

                    b.ToTable("maden_data", (string)null);
                });

            modelBuilder.Entity("InvestAI.Models.OsbPresence", b =>
                {
                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("durum");

                    b.Property<string>("Il")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("il");

                    b.Property<string>("Ilce")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ilce");

                    b.Property<string>("OsbAdi")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("osb_adi");

                    b.Property<int>("OsbKapasite")
                        .HasColumnType("integer")
                        .HasColumnName("osb_kapasite");

                    b.ToTable("osb_presence", (string)null);
                });

            modelBuilder.Entity("InvestAI.Models.PopulationGrowth", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("district");

                    b.Property<int>("Increase")
                        .HasColumnType("integer")
                        .HasColumnName("increase");

                    b.Property<decimal>("IncreaseRate")
                        .HasColumnType("numeric")
                        .HasColumnName("increase_rate");

                    b.Property<int>("Population2024")
                        .HasColumnType("integer")
                        .HasColumnName("population_2024");

                    b.Property<int>("Population2025")
                        .HasColumnType("integer")
                        .HasColumnName("population_2025");

                    b.Property<string>("Trend")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trend");

                    b.HasKey("Id");

                    b.ToTable("population_growth", (string)null);
                });

            modelBuilder.Entity("InvestAI.Models.PortData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PortDatas");
                });

            modelBuilder.Entity("InvestAI.Models.ProvinceSectorDistribution", b =>
                {
                    b.Property<int>("EmployeeCount")
                        .HasColumnType("integer")
                        .HasColumnName("employee_count");

                    b.Property<string>("Il")
                        .HasColumnType("text")
                        .HasColumnName("il");

                    b.Property<double>("Percentage")
                        .HasColumnType("double precision")
                        .HasColumnName("percentage");

                    b.Property<string>("SectorCode")
                        .HasColumnType("text")
                        .HasColumnName("sector_code");

                    b.Property<string>("SectorName")
                        .HasColumnType("text")
                        .HasColumnName("sector_name");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.ToTable("province_sector_distribution", (string)null);
                });

            modelBuilder.Entity("InvestAI.Models.ProvinceSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DominantSectorCode")
                        .HasColumnType("text")
                        .HasColumnName("dominant_sector_code");

                    b.Property<string>("DominantSectorName")
                        .HasColumnType("text")
                        .HasColumnName("dominant_sector_name");

                    b.Property<string>("Il")
                        .HasColumnType("text")
                        .HasColumnName("il");

                    b.Property<int>("TotalEstimatedEmployment")
                        .HasColumnType("integer")
                        .HasColumnName("total_estimated_employment");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.ToTable("province_summary", (string)null);
                });

            modelBuilder.Entity("InvestAI.Models.RailwayData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RailwayDatas");
                });

            modelBuilder.Entity("InvestAI.Models.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("InfrastructureScore")
                        .HasColumnType("integer");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Population")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PopulationUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WikidataId")
                        .HasColumnType("text");

                    b.Property<int>("Workforce")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("InvestAI.Models.RegionResource", b =>
                {
                    b.Property<int>("RegionId")
                        .HasColumnType("integer");

                    b.Property<int>("ResourceId")
                        .HasColumnType("integer");

                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.HasKey("RegionId", "ResourceId");

                    b.HasIndex("ResourceId");

                    b.ToTable("RegionResources");
                });

            modelBuilder.Entity("InvestAI.Models.RegionSector", b =>
                {
                    b.Property<int>("RegionId")
                        .HasColumnType("integer");

                    b.Property<int>("SectorId")
                        .HasColumnType("integer");

                    b.Property<int>("Strength")
                        .HasColumnType("integer");

                    b.HasKey("RegionId", "SectorId");

                    b.HasIndex("SectorId");

                    b.ToTable("RegionSectors");
                });

            modelBuilder.Entity("InvestAI.Models.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Quantity")
                        .HasColumnType("real");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("InvestAI.Models.RuzgarSantrali", b =>
                {
                    b.Property<string>("Firma")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("firma");

                    b.Property<string>("Il")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("il");

                    b.Property<decimal>("KuruluGucMw")
                        .HasColumnType("numeric")
                        .HasColumnName("kurulu_guc_mw");

                    b.Property<string>("SantralAdi")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("santral_adi");

                    b.ToTable("ruzgar_santralleri", (string)null);
                });

            modelBuilder.Entity("InvestAI.Models.Sector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("EmploymentRate")
                        .HasColumnType("real");

                    b.Property<float>("GrowthRate")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Sectors");
                });

            modelBuilder.Entity("InvestAI.Models.SwotAnalysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AiGenerated")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Opportunities")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RegionId")
                        .HasColumnType("integer");

                    b.Property<string>("Strengths")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Threats")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Weaknesses")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("SwotAnalyses");
                });

            modelBuilder.Entity("InvestAI.Models.TesvikBolgesi", b =>
                {
                    b.Property<string>("Il")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("il");

                    b.Property<int>("TesvikBolge")
                        .HasColumnType("integer")
                        .HasColumnName("tesvik_bolge");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.ToTable("tesvik_bolgesi", (string)null);
                });

            modelBuilder.Entity("InvestAI.Models.WorldBankIndicator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IndicatorCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IndicatorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Value")
                        .HasColumnType("numeric");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("WorldBankIndicators");
                });

            modelBuilder.Entity("InvestAI.Models.YerelKalkinmaWide", b =>
                {
                    b.Property<string>("Il")
                        .HasColumnType("text")
                        .HasColumnName("il");

                    b.Property<string>("Konu1")
                        .HasColumnType("text")
                        .HasColumnName("konu_1");

                    b.Property<string>("Konu2")
                        .HasColumnType("text")
                        .HasColumnName("konu_2");

                    b.Property<string>("Konu3")
                        .HasColumnType("text")
                        .HasColumnName("konu_3");

                    b.Property<string>("Konu4")
                        .HasColumnType("text")
                        .HasColumnName("konu_4");

                    b.Property<int>("Yil")
                        .HasColumnType("integer")
                        .HasColumnName("yil");

                    b.ToTable("yerel_kalkinma_wide", (string)null);
                });

            modelBuilder.Entity("InvestAI.Models.InvestmentSuggestion", b =>
                {
                    b.HasOne("InvestAI.Models.Region", "Region")
                        .WithMany("InvestmentSuggestions")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("InvestAI.Models.RegionResource", b =>
                {
                    b.HasOne("InvestAI.Models.Region", "Region")
                        .WithMany("RegionResources")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvestAI.Models.Resource", "Resource")
                        .WithMany("RegionResources")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("InvestAI.Models.RegionSector", b =>
                {
                    b.HasOne("InvestAI.Models.Region", "Region")
                        .WithMany("RegionSectors")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvestAI.Models.Sector", "Sector")
                        .WithMany("RegionSectors")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("InvestAI.Models.SwotAnalysis", b =>
                {
                    b.HasOne("InvestAI.Models.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("InvestAI.Models.Region", b =>
                {
                    b.Navigation("InvestmentSuggestions");

                    b.Navigation("RegionResources");

                    b.Navigation("RegionSectors");
                });

            modelBuilder.Entity("InvestAI.Models.Resource", b =>
                {
                    b.Navigation("RegionResources");
                });

            modelBuilder.Entity("InvestAI.Models.Sector", b =>
                {
                    b.Navigation("RegionSectors");
                });
#pragma warning restore 612, 618
        }
    }
}
